
name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Docker
      run: docker build -t tutorial/hello-world . && docker run -dp 5001:5001 tutorial/hello-world
